### PR TITLE
Order

### PR DESCRIPTION
**Pull request by giangnguyen13**

### CODE REVIEW

**Comment by giangnguyen13** [comment]
Need design for shipping address / billing address

**Comment by franndyabreu** [comment]
Hey @giangnguyen13 , I think we should create issues and assign them to ourself when working on something because I already submitted a pull request about changes in the product model and how to get all the products and a particular product from Mongo Atlas. In that way, we avoid doing things that other person is doing already, like now

**Comment by franndyabreu** [comment]
> Hey @giangnguyen13 , I think we should create issues and assign them to ourself when working on something because I already submitted a pull request about changes in the product model and how to get all the products and a particular product from Mongo Atlas. In that way, we avoid doing things that other person is doing already, like now

Also, it would be better that when submitting a pull request to be about one particular use case (eg. Checkout Screen only) rather than more than one. So instead of creating one pull request that has a lot of changes in different screens and models, we could create one pull request per screen/model, in that way it would be easier to review for everyone.

**Comment by franndyabreu** [comment]
> Hey @giangnguyen13 , I think we should create issues and assign them to ourself when working on something because I already submitted a pull request (PR #12) about changes in the product model and how to get all the products and a particular product from Mongo Atlas. In that way, we avoid doing things that other person is doing already, like now

**Comment by giangnguyen13** [comment]
> > Hey @giangnguyen13 , I think we should create issues and assign them to ourself when working on something because I already submitted a pull request about changes in the product model and how to get all the products and a particular product from Mongo Atlas. In that way, we avoid doing things that other person is doing already, like now
> 
> Also, it would be better that when submitting a pull request to be about one particular use case (eg. Checkout Screen only) rather than more than one. So instead of creating one pull request that has a lot of changes in different screens and models, we could create one pull request per screen/model, in that way it would be easier to review for everyone.

Thank @franndyabreu , I do that for next time. For now, I will merge your branch first and resolve any conflicts in my current PR

**Comment by giangnguyen13** [comment]
close this MR since there is merge into `merging_branch` and resolve all the conflicts

**Pull request closed without merging**
